# Generated by Django 4.2.4 on 2023-08-15 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page", models.CharField(max_length=25)),
                ("visit_time", models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
        ),
    ]
