# Generated by Django 4.2.4 on 2023-09-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_job_end_date_alter_job_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="job_number",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
