### Site settings
baseURL = 'https://ajpcloudblog.com/'
languageCode = 'en-au'
title = 'AJP Cloud Blog'
theme = 'hugo-PaperMod'

[params]
  socialIcons = [
    { name = 'github', url = 'https://github.com/ajpotts01' },
    { name = 'linkedin', url = 'https://www.linkedin.com/in/alexander-potts-9b4a41aa/' }
  ]
  