name: cd-application
on:
  push:
    branches: [ main ]
    paths:
      - "application/**"
  workflow_dispatch:

# TODO: Consider workload identity federation
env:
  gcp_project: ${{ secrets.GCP_PROJECT }}
  gcp_sa_key: ${{ secrets.GCP_SA_KEY }}
  gcp_gcr_name: ${{ secrets.GCP_GCR_NAME }}
  gcp_region: ${{ secrets.GCP_REGION }}
  django_allowed_hosts: ${{ secrets.DJANGO_ALLOWED_HOSTS }}

jobs:
  ci:
    runs-on: ubuntu-22.04 # Docker image runs on Debian, but should be OK here
    env:
      PIPENV_VENV_IN_PROJECT: 1

    steps:
      # Get PR branch
      - name: Source code - checkout PR
        uses: actions/checkout@v3

      # Python setup
      - name: Python - initial setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      
      # Gather Python deps - for gcloud build submit
      - name: Python - gather dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv==2023.7.23
          pipenv install --system
          pip freeze > application/requirements.txt

      # Deployment - activate service account
      - name: Deployment - activate service account
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ env.gcp_sa_key }}

      # Deployment - set up gcloud CLI
      - name: Deployment - set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: ">= 363.0.0"

      # Deployment - docker auth
      - name: Deployment - configure docker
        run: |
          gcloud auth configure-docker

      # Deployment - Submit to Cloud Build
      - name: Deployment - submit to Cloud Build
        run: |
          cd application/
          gcloud builds submit \
          --region=${{ env.gcp_region }} \
          -t gcr.io/${{ env.gcp_project }}/${{ env.gcp_gcr_name }} \
          .

      # Deploy to Cloud Run
      - name: Deployment - submit to Cloud Run
        run: |
          gcloud run deploy \
          ${{ env.gcp_gcr_name }} \
          --image=gcr.io/${{ env.gcp_project }}/${{ env.gcp_gcr_name }} \
          --region=${{ env.gcp_region }} \
          --allow-unauthenticated \
          --set-env-vars ^@^ALLOWED_HOST_URLS=${{ env.django_allowed_hosts }}
