name: cd-hugo-application
on:
  push:
    branches: [ main ]
    paths:
      - "application/**"
  workflow_dispatch:

env:
  gcp_project: ${{ secrets.GCP_PROJECT }}
  sa_creds: ${{ secrets.FIREBASE_SA_CREDS }}
  hugo_version: 0.119.0

jobs:
  cd:
    runs-on: ubuntu-22.04

    steps:
      - name: Source code - checkout main
        uses: actions/checkout@v3
      
      - name: Setup Firebase
        run: |
          curl -sL firebase.tools | bash

      - name: Setup Hugo
        run: |
          curl -L "https://github.com/gohugoio/hugo/releases/download/v${{ env.hugo_version }}/hugo_${{ env.hugo_version }}_Linux-64bit.tar.gz" --output hugo.tar.gz
          tar -xvzf hugo.tar.gz
          sudo mv hugo /usr/local/bin

      - name: Build site
        working-directory: application/cloud_blog
        run: hugo

      - name: Deploy site
        working-directory: application/cloud_blog
        run: |
          echo $sa_creds > $HOME/sa.json
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/sa.json
          firebase deploy --only hosting
          rm $HOME/sa.json
          unset GOOGLE_APPLICATION_CREDENTIALS